-- ==========================================================
-- ElderGuard Database Schema
-- Based on the ElderGuard Final UML Class Diagram
-- ==========================================================

-- Disable foreign key checks during creation/reset
SET FOREIGN_KEY_CHECKS = 0;

-- 1. USERS TABLE
-- Represents accounts for Parents, Caregivers, and Doctors (specializations of users)
CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone_number VARCHAR(25) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('parent', 'caregiver', 'doctor') NOT NULL DEFAULT 'parent',
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. ADMIN TABLE
-- Manages user accounts (activate / deactivate)
CREATE TABLE IF NOT EXISTS admins (
  admin_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. ELDERLY PERSON PROFILE TABLE
-- Managed and created by Parent, monitored by Caregiver and Doctor
CREATE TABLE IF NOT EXISTS elderly_profiles (
  elderly_id INT AUTO_INCREMENT PRIMARY KEY,
  parent_id INT NOT NULL,
  caregiver_id INT NULL,
  doctor_id INT NULL,
  full_name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender VARCHAR(20) NOT NULL,
  address VARCHAR(255) NOT NULL,
  emergency_contact VARCHAR(50) NOT NULL,
  medical_information TEXT NULL,
  doctor_name VARCHAR(100) NULL,
  doctor_phone VARCHAR(50) NULL,
  doctor_specialty VARCHAR(100) NULL,
  doctor_hospital VARCHAR(150) NULL,
  doctor_email VARCHAR(150) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (caregiver_id) REFERENCES users(user_id) ON DELETE SET NULL,
  FOREIGN KEY (doctor_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. DAILY ACTIVITY TABLE
-- Daily routines and schedule items associated with an elderly person
CREATE TABLE IF NOT EXISTS daily_activities (
  activity_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  description TEXT NULL,
  status ENUM('pending', 'completed') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. LOCATION TABLE
-- GPS tracking records for the elderly person
CREATE TABLE IF NOT EXISTS locations (
  location_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL,
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. REMINDER TABLE
-- Medication, appointment, and health reminders set by Parent
CREATE TABLE IF NOT EXISTS reminders (
  reminder_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  description TEXT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'medication',
  status ENUM('active', 'completed', 'dismissed') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. NOTIFICATION TABLE
-- Notifications sent to users (Parent / Caregiver)
CREATE TABLE IF NOT EXISTS notifications (
  notification_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('unread', 'read') NOT NULL DEFAULT 'unread',
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. ALERT TABLE
-- Emergency and critical events generated by IoT device / Geofence
CREATE TABLE IF NOT EXISTS alerts (
  alert_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL,
  notification_id INT NULL,
  description VARCHAR(255) NOT NULL,
  date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE,
  FOREIGN KEY (notification_id) REFERENCES notifications(notification_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. IOT DEVICE TABLE
-- Wearable monitoring device paired to the elderly person
CREATE TABLE IF NOT EXISTS iot_devices (
  device_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NULL UNIQUE,
  device_name VARCHAR(100) NOT NULL,
  last_connection DATETIME NULL,
  status ENUM('connected', 'disconnected') NOT NULL DEFAULT 'disconnected',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. GEOFENCE TABLE
-- Safe boundary configured by Parent around a central location
CREATE TABLE IF NOT EXISTS geofences (
  geofence_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL UNIQUE,
  center_latitude DECIMAL(10, 8) NOT NULL,
  center_longitude DECIMAL(11, 8) NOT NULL,
  radius DOUBLE NOT NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. REPORT TABLE
-- Summary reports generated by Parent
CREATE TABLE IF NOT EXISTS reports (
  report_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL,
  parent_id INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  period VARCHAR(50) NOT NULL,
  generated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  content LONGTEXT NOT NULL,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE,
  FOREIGN KEY (parent_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. CLINICAL NOTES TABLE
-- Medical consultation notes & recommendations recorded by Doctor
CREATE TABLE IF NOT EXISTS clinical_notes (
  note_id INT AUTO_INCREMENT PRIMARY KEY,
  elderly_id INT NOT NULL,
  doctor_id INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  note_content TEXT NOT NULL,
  recommendations TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (elderly_id) REFERENCES elderly_profiles(elderly_id) ON DELETE CASCADE,
  FOREIGN KEY (doctor_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
